services:
  app:
    image: akadnya:latest
    container_name: akadnya-app
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: https://akadnya.com
      DB_CONNECTION: mysql
      DB_HOST: 192.168.18.250
      DB_PORT: 3306
      DB_DATABASE: myakad
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PAYMENT_SERVICE_URL: http://payment-service-app:8080
      PAYMENT_SERVICE_PUBLIC_URL: https://pay.refaadstack.com
      AKADNYA_PRODUCT_KEY: ${AKADNYA_PRODUCT_KEY}
      AKADNYA_CALLBACK_SECRET: ${AKADNYA_CALLBACK_SECRET}
    volumes:
      - ./storage/app/public:/app/storage/app/public
      - ./storage/logs:/app/storage/logs
    networks:
      - infra_default

networks:
  infra_default:
    external: true
